steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/t-operative-275118/my-repo/my-node-app:latest',
      '.'
    ]

images:
  - 'us-central1-docker.pkg.dev/t-operative-275118/my-repo/my-node-app:latest'
